<script src="<c:url value="/js/library-js/jquery-2.1.4.min.js"/>" type="text/javascript"></script>
<script src="<c:url value="/js/library-js/html5shiv.min.js"/>" type="text/javascript"></script>
<script src="<c:url value="/js/library-js/respond.min.js"/>" type="text/javascript"></script>
<script src="<c:url value="/stylesheet/stilize/js/stilize.js"/>" type="text/javascript"></script>
<script src="<c:url value="/js/library-js/library-js.js"/>" type="text/javascript"></script>
<script src="<c:url value="/js/library-js/pattern.js"/>" type="text/javascript"></script>
<script src="<c:url value="/js/library-js/select.js"/>" type="text/javascript"></script>
<script src="<c:url value="/js/library-js/loadgrid.js"/>" type="text/javascript"></script>
<script src="<c:url value="/js/library-js/format.js"/>" type="text/javascript"></script>
<script src="<c:url value="/stylesheet/stilize/plugins/select2/select2.js"/>" type="text/javascript"></script>