<script src="<c:url value="/assets/css/stilize/stilize.min.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/ssearch/ssearch.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/http.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/jlib.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/autoCompleteOff.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/checkGrid.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/loadgrid.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/mask.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/parametrosWebDynamic.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/pattern.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/select.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/services.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/textarea.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/jlib/upper.js"/>" type="text/javascript"></script>
<script src="<c:url value="/assets/js/puppis.js"/>" type="text/javascript"></script>